name: Extract System IMG (Artifact)

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Direct ROM zip URL"
        required: true

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y brotli python3 unzip git wget

      - name: Download ROM
        run: |
          wget "${{ github.event.inputs.ROM_URL }}" -O rom.zip

      - name: Extract ROM
        run: unzip rom.zip -d rom

      - name: Find system files
        run: |
          cd rom
          cp $(find . -name "system.new.dat.br" | head -n 1) ../system.new.dat.br
          cp $(find . -name "system.transfer.list" | head -n 1) ../system.transfer.list

      - name: Decompress brotli
        run: brotli --decompress system.new.dat.br -o system.new.dat

      - name: Convert DAT → IMG
        run: |
          git clone https://github.com/xpirt/sdat2img.git
          python3 sdat2img/sdat2img.py system.transfer.list system.new.dat system.img

      - name: Upload system.img as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: system-img
          path: system.img
          compression-level: 0
